title: distrosetta.com
description: A Rosetta Stone for Linux distributions
theme: just-the-docs

url: https://distrosetta.com

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
